# 🎨 Data Designer Tutorial: The Basics

#### 📚 What you'll learn

This notebook demonstrates the basics of Data Designer by generating a simple product review dataset.

### 📦 Import Data Designer

- `data_designer.config` provides access to the configuration API.

- `DataDesigner` is the main interface for data generation.

In [9]:
# ! export NVIDIA_API_KEY="" # TODO copy your nvidia-api-key here:
# https://build.nvidia.com/settings/api-keys
# login with you email box (or register)
# click "Generate API key"

In [2]:
! pip install data_designer

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: data_designer in /usr/local/lib/python3.10/dist-packages (0.5.6)
Requirement already satisfied: data-designer-config==0.5.6 in /usr/local/lib/python3.10/dist-packages (from data_designer) (0.5.6)
Requirement already satisfied: data-designer-engine==0.5.6 in /usr/local/lib/python3.10/dist-packages (from data_designer) (0.5.6)
Requirement already satisfied: prompt-toolkit<4,>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from data_designer) (3.0.43)
Requirement already satisfied: typer<1,>=0.12.0 in /usr/local/lib/python3.10/dist-packages (from data_designer) (0.12.3)
Requirement already satisfied: jinja2<4,>=3.1.6 in /usr/local/lib/python3.10/dist-packages (from data-designer-config==0.5.6->data_designer) (3.1.6)
Requirement already satisfied: numpy<3,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from data-designer-config==0.5.6->data_designer) (1.24.4)
Requirement already satisfied: pandas<3,>=2.3.3 in /usr/local/lib/python3.10/dist-packages (from data-designer-config==0.5.6->data_designer) (2.3.3)
Requirement already satisfied: pillow<13,>=12.1.1 in /usr/local/lib/python3.10/dist-packages (from data-designer-config==0.5.6->data_designer) (12.2.0)
Requirement already satisfied: pyarrow<20,>=19.0.1 in /usr/local/lib/python3.10/dist-packages (from data-designer-config==0.5.6->data_designer) (19.0.1)
Requirement already satisfied: pydantic<3,>=2.9.2 in /usr/local/lib/python3.10/dist-packages (from pydantic[email]<3,>=2.9.2->data-designer-config==0.5.6->data_designer) (2.13.0)
Requirement already satisfied: pygments<3,>=2.20 in /usr/local/lib/python3.10/dist-packages (from data-designer-config==0.5.6->data_designer) (2.20.0)
Requirement already satisfied: python-json-logger<4,>=3 in /usr/local/lib/python3.10/dist-packages (from data-designer-config==0.5.6->data_designer) (3.3.0)
Requirement already satisfied: pyyaml<7,>=6.0.1 in /usr/local/lib/python3.10/dist-packages (from data-designer-config==0.5.6->data_designer) (6.0.1)
Requirement already satisfied: requests<3,>=2.33 in /usr/local/lib/python3.10/dist-packages (from data-designer-config==0.5.6->data_designer) (2.33.1)
Requirement already satisfied: rich<15,>=13.7.1 in /usr/local/lib/python3.10/dist-packages (from data-designer-config==0.5.6->data_designer) (13.7.1)
Requirement already satisfied: anyascii<1,>=0.3.3 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (0.3.3)
Requirement already satisfied: chardet<6,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (5.2.0)
Requirement already satisfied: duckdb<2,>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (1.5.2)
Requirement already satisfied: faker<21,>=20.1.0 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (20.1.0)
Requirement already satisfied: fsspec<2026,>=2025.3.0 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (2025.12.0)
Requirement already satisfied: httpx-retries<1,>=0.4.2 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (0.4.6)
Requirement already satisfied: httpx<1,>=0.27.2 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (0.28.1)
Requirement already satisfied: huggingface-hub<2,>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (1.10.2)
Requirement already satisfied: json-repair<1,>=0.48.0 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (0.59.4)
Requirement already satisfied: jsonpath-rust-bindings<2,>=1.0 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (1.1.1)
Requirement already satisfied: jsonschema<5,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (4.21.1)
Requirement already satisfied: lxml<7,>=6.0.2 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (6.0.4)
Requirement already satisfied: marko<3,>=2.1.2 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (2.2.2)
Requirement already satisfied: mcp<2,>=1.26.0 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (1.27.0)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (3.3)
Requirement already satisfied: ruff<1,>=0.14.10 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (0.15.10)
Requirement already satisfied: scipy<2,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (1.12.0)
Requirement already satisfied: sqlfluff<4,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (3.5.0)
Requirement already satisfied: tiktoken<1,>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from data-designer-engine==0.5.6->data_designer) (0.12.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit<4,>=3.0.0->data_designer) (0.2.13)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1,>=0.12.0->data_designer) (8.1.7)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from typer<1,>=0.12.0->data_designer) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1,>=0.12.0->data_designer) (1.5.4)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker<21,>=20.1.0->data-designer-engine==0.5.6->data_designer) (2.9.0.post0)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.27.2->data-designer-engine==0.5.6->data_designer) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.27.2->data-designer-engine==0.5.6->data_designer) (2024.2.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.27.2->data-designer-engine==0.5.6->data_designer) (1.0.5)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.27.2->data-designer-engine==0.5.6->data_designer) (3.6)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1,>=0.27.2->data-designer-engine==0.5.6->data_designer) (0.14.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<2,>=1.0.1->data-designer-engine==0.5.6->data_designer) (3.13.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<2,>=1.0.1->data-designer-engine==0.5.6->data_designer) (1.4.3)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<2,>=1.0.1->data-designer-engine==0.5.6->data_designer) (23.2)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<2,>=1.0.1->data-designer-engine==0.5.6->data_designer) (4.66.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2<4,>=3.1.6->data-designer-config==0.5.6->data_designer) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema<5,>=4.0.0->data-designer-engine==0.5.6->data_designer) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema<5,>=4.0.0->data-designer-engine==0.5.6->data_designer) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema<5,>=4.0.0->data-designer-engine==0.5.6->data_designer) (0.33.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema<5,>=4.0.0->data-designer-engine==0.5.6->data_designer) (0.18.0)
Requirement already satisfied: httpx-sse>=0.4 in /usr/local/lib/python3.10/dist-packages (from mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (0.4.3)
Requirement already satisfied: pydantic-settings>=2.5.2 in /usr/local/lib/python3.10/dist-packages (from mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (2.13.1)
Requirement already satisfied: pyjwt>=2.10.1 in /usr/local/lib/python3.10/dist-packages (from pyjwt[crypto]>=2.10.1->mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (2.12.1)
Requirement already satisfied: python-multipart>=0.0.9 in /usr/local/lib/python3.10/dist-packages (from mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (0.0.26)
Requirement already satisfied: sse-starlette>=1.6.1 in /usr/local/lib/python3.10/dist-packages (from mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (3.3.4)
Requirement already satisfied: starlette>=0.27 in /usr/local/lib/python3.10/dist-packages (from mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (1.0.0)
Requirement already satisfied: typing-inspection>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (0.4.2)
Requirement already satisfied: uvicorn>=0.31.1 in /usr/local/lib/python3.10/dist-packages (from mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=2.3.3->data-designer-config==0.5.6->data_designer) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=2.3.3->data-designer-config==0.5.6->data_designer) (2024.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=2.9.2->pydantic[email]<3,>=2.9.2->data-designer-config==0.5.6->data_designer) (0.6.0)
Requirement already satisfied: pydantic-core==2.46.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=2.9.2->pydantic[email]<3,>=2.9.2->data-designer-config==0.5.6->data_designer) (2.46.0)
Requirement already satisfied: email-validator>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pydantic[email]<3,>=2.9.2->data-designer-config==0.5.6->data_designer) (2.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.33->data-designer-config==0.5.6->data_designer) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.33->data-designer-config==0.5.6->data_designer) (1.26.19)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<15,>=13.7.1->data-designer-config==0.5.6->data_designer) (3.0.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.10/dist-packages (from sqlfluff<4,>=3.2.0->data-designer-engine==0.5.6->data_designer) (4.2.0)
Requirement already satisfied: colorama>=0.3 in /usr/local/lib/python3.10/dist-packages (from sqlfluff<4,>=3.2.0->data-designer-engine==0.5.6->data_designer) (0.4.6)
Requirement already satisfied: diff-cover>=2.5.0 in /usr/local/lib/python3.10/dist-packages (from sqlfluff<4,>=3.2.0->data-designer-engine==0.5.6->data_designer) (10.2.0)
Requirement already satisfied: pathspec in /usr/local/lib/python3.10/dist-packages (from sqlfluff<4,>=3.2.0->data-designer-engine==0.5.6->data_designer) (0.12.1)
Requirement already satisfied: pytest in /usr/local/lib/python3.10/dist-packages (from sqlfluff<4,>=3.2.0->data-designer-engine==0.5.6->data_designer) (8.0.2)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from sqlfluff<4,>=3.2.0->data-designer-engine==0.5.6->data_designer) (2023.12.25)
Requirement already satisfied: tblib in /usr/local/lib/python3.10/dist-packages (from sqlfluff<4,>=3.2.0->data-designer-engine==0.5.6->data_designer) (3.0.0)
Requirement already satisfied: tomli in /usr/local/lib/python3.10/dist-packages (from sqlfluff<4,>=3.2.0->data-designer-engine==0.5.6->data_designer) (2.0.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from anyio->httpx<1,>=0.27.2->data-designer-engine==0.5.6->data_designer) (1.2.0)
Requirement already satisfied: pluggy<2,>=0.13.1 in /usr/local/lib/python3.10/dist-packages (from diff-cover>=2.5.0->sqlfluff<4,>=3.2.0->data-designer-engine==0.5.6->data_designer) (1.4.0)
Requirement already satisfied: dnspython>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from email-validator>=2.0.0->pydantic[email]<3,>=2.9.2->data-designer-config==0.5.6->data_designer) (2.6.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<15,>=13.7.1->data-designer-config==0.5.6->data_designer) (0.1.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.10/dist-packages (from pydantic-settings>=2.5.2->mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (1.0.1)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.10/dist-packages (from pyjwt[crypto]>=2.10.1->mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (46.0.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker<21,>=20.1.0->data-designer-engine==0.5.6->data_designer) (1.16.0)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest->sqlfluff<4,>=3.2.0->data-designer-engine==0.5.6->data_designer) (2.0.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=2.0.0->cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->mcp<2,>=1.26.0->data-designer-engine==0.5.6->data_designer) (2.21)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python -m pip install --upgrade pip

In [3]:
import data_designer.config as dd
from data_designer.interface import DataDesigner

/usr/local/lib/python3.10/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### ⚙️ Initialize the Data Designer interface

- `DataDesigner` is the main object responsible for managing the data generation process.

- When initialized without arguments, the [default model providers](https://nvidia-nemo.github.io/DataDesigner/latest/concepts/models/default-model-settings/) are used.

In [4]:
data_designer = DataDesigner()

### 🎛️ Define model configurations

- Each `ModelConfig` defines a model that can be used during the generation process.

- The "model alias" is used to reference the model in the Data Designer config (as we will see below).

- The "model provider" is the external service that hosts the model (see the [model config](https://nvidia-nemo.github.io/DataDesigner/latest/concepts/models/default-model-settings/) docs for more details).

- By default, we use [build.nvidia.com](https://build.nvidia.com/models) as the model provider.

In [5]:
# This name is set in the model provider configuration.
MODEL_PROVIDER = "nvidia"

# The model ID is from build.nvidia.com.
MODEL_ID = "nvidia/nemotron-3-nano-30b-a3b"

# We choose this alias to be descriptive for our use case.
MODEL_ALIAS = "nemotron-nano-v3"

model_configs = [
    dd.ModelConfig(
        alias=MODEL_ALIAS,
        model=MODEL_ID,
        provider=MODEL_PROVIDER,
        inference_parameters=dd.ChatCompletionInferenceParams(
            temperature=1.0,
            top_p=1.0,
            max_tokens=2048,
            extra_body={"chat_template_kwargs": {"enable_thinking": False}},
        ),
    )
]

### 🏗️ Initialize the Data Designer Config Builder

- The Data Designer config defines the dataset schema and generation process.

- The config builder provides an intuitive interface for building this configuration.

- The list of model configs is provided to the builder at initialization.

In [6]:
config_builder = dd.DataDesignerConfigBuilder(model_configs=model_configs)

## 🎲 Getting started with sampler columns

- Sampler columns offer non-LLM based generation of synthetic data.

- They are particularly useful for **steering the diversity** of the generated data, as we demonstrate below.

<br>

You can view available samplers using the config builder's `info` property:

In [7]:
config_builder.info.display("samplers")

─────────────────────────────────────────── NeMo Data Designer Samplers ───────────────────────────────────────────

┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ Type               ┃ Parameter                ┃ Data Type                         ┃ Required ┃ Constraints      ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ bernoulli          │ p                        │ number                            │    ✓     │ >= 0.0, <= 1.0   │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ bernoulli_mixture  │ p                        │ number                            │    ✓     │ >= 0.0, <= 1.0   │
│                    │ dist_name                │ string                            │    ✓     │                  │
│                    │ dist_params              │ dict                              │    ✓     │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ binomial           │ n                        │ integer                           │    ✓     │                  │
│                    │ p                        │ number                            │    ✓     │ >= 0.0, <= 1.0   │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ category           │ values                   │ string[] | integer[] | number[]   │    ✓     │ len > 1          │
│                    │ weights                  │ number[] | null                   │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ datetime           │ start                    │ string                            │    ✓     │                  │
│                    │ end                      │ string                            │    ✓     │                  │
│                    │ unit                     │ string                            │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ gaussian           │ mean                     │ number                            │    ✓     │                  │
│                    │ stddev                   │ number                            │    ✓     │                  │
│                    │ decimal_places           │ integer | null                    │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ person             │ locale                   │ string                            │          │                  │
│                    │ sex                      │ string | null                     │          │                  │
│                    │ city                     │ string | string[] | null          │          │                  │
│                    │ age_range                │ integer[]                         │          │ len > 2, len < 2 │
│                    │ select_field_values      │ object | null                     │          │                  │
│                    │ with_synthetic_personas  │ boolean                           │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ person_from_faker  │ locale                   │ string                            │          │                  │
│                    │ sex                      │ string | null                     │          │                  │
│                    │ city                     │ string | string[] | null          │          │                  │
│                    │ age_range                │ integer[]                         │          │ len > 2, len < 2 │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ poisson            │ mean                     │ number                            │    ✓     │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ scipy              │ dist_name                │ string                            │    ✓     │                  │
│                    │ dist_params              │ dict                              │    ✓     │                  │
│                    │ decimal_places           │ integer | null                    │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ subcategory        │ category                 │ string                            │    ✓     │                  │
│                    │ values                   │ dict                              │    ✓     │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ timedelta          │ dt_min                   │ integer                           │    ✓     │ >= 0             │
│                    │ dt_max                   │ integer                           │    ✓     │ > 0              │
│                    │ reference_column_name    │ string                            │    ✓     │                  │
│                    │ unit                     │ string                            │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ uniform            │ low                      │ number                            │    ✓     │                  │
│                    │ high                     │ number                            │    ✓     │                  │
│                    │ decimal_places           │ integer | null                    │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ uuid               │ prefix                   │ string | null                     │          │                  │
│                    │ short_form               │ boolean                           │          │                  │
│                    │ uppercase                │ boolean                           │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
└────────────────────┴──────────────────────────┴───────────────────────────────────┴──────────┴──────────────────┘

Let's start designing our product review dataset by adding product category and subcategory columns.

In [8]:
config_builder.add_column(
    dd.SamplerColumnConfig(
        name="product_category",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(
            values=[
                "Electronics",
                "Clothing",
                "Home & Kitchen",
                "Books",
                "Home Office",
            ],
        ),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="product_subcategory",
        sampler_type=dd.SamplerType.SUBCATEGORY,
        params=dd.SubcategorySamplerParams(
            category="product_category",
            values={
                "Electronics": [
                    "Smartphones",
                    "Laptops",
                    "Headphones",
                    "Cameras",
                    "Accessories",
                ],
                "Clothing": [
                    "Men's Clothing",
                    "Women's Clothing",
                    "Winter Coats",
                    "Activewear",
                    "Accessories",
                ],
                "Home & Kitchen": [
                    "Appliances",
                    "Cookware",
                    "Furniture",
                    "Decor",
                    "Organization",
                ],
                "Books": [
                    "Fiction",
                    "Non-Fiction",
                    "Self-Help",
                    "Textbooks",
                    "Classics",
                ],
                "Home Office": [
                    "Desks",
                    "Chairs",
                    "Storage",
                    "Office Supplies",
                    "Lighting",
                ],
            },
        ),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="target_age_range",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(values=["18-25", "25-35", "35-50", "50-65", "65+"]),
    )
)

# Optionally validate that the columns are configured correctly.
data_designer.validate(config_builder)

[13:14:47] [INFO] ✅ Validation passed

Next, let's add samplers to generate data related to the customer and their review.

In [10]:
config_builder.add_column(
    dd.SamplerColumnConfig(
        name="customer",
        sampler_type=dd.SamplerType.PERSON_FROM_FAKER,
        params=dd.PersonFromFakerSamplerParams(age_range=[18, 70], locale="en_US"),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="number_of_stars",
        sampler_type=dd.SamplerType.UNIFORM,
        params=dd.UniformSamplerParams(low=1, high=5),
        convert_to="int",  # Convert the sampled float to an integer.
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="review_style",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(
            values=["rambling", "brief", "detailed", "structured with bullet points"],
            weights=[1, 2, 2, 1],
        ),
    )
)

data_designer.validate(config_builder)

[13:18:03] [INFO] ✅ Validation passed

## 🦜 LLM-generated columns

- The real power of Data Designer comes from leveraging LLMs to generate text, code, and structured data.

- When prompting the LLM, we can use Jinja templating to reference other columns in the dataset.

- As we see below, nested json fields can be accessed using dot notation.

In [11]:
config_builder.add_column(
    dd.LLMTextColumnConfig(
        name="product_name",
        prompt=(
            "You are a helpful assistant that generates product names. DO NOT add quotes around the product name.\n\n"
            "Come up with a creative product name for a product in the '{{ product_category }}' category, focusing "
            "on products related to '{{ product_subcategory }}'. The target age range of the ideal customer is "
            "{{ target_age_range }} years old. Respond with only the product name, no other text."
        ),
        model_alias=MODEL_ALIAS,
    )
)

config_builder.add_column(
    dd.LLMTextColumnConfig(
        name="customer_review",
        prompt=(
            "You are a customer named {{ customer.first_name }} from {{ customer.city }}, {{ customer.state }}. "
            "You are {{ customer.age }} years old and recently purchased a product called {{ product_name }}. "
            "Write a review of this product, which you gave a rating of {{ number_of_stars }} stars. "
            "The style of the review should be '{{ review_style }}'. "
            "Respond with only the review, no other text."
        ),
        model_alias=MODEL_ALIAS,
    )
)

data_designer.validate(config_builder)

[13:18:09] [INFO] ✅ Validation passed

### 🔁 Iteration is key – preview the dataset!

1. Use the `preview` method to generate a sample of records quickly.

2. Inspect the results for quality and format issues.

3. Adjust column configurations, prompts, or parameters as needed.

4. Re-run the preview until satisfied.

In [12]:
preview = data_designer.preview(config_builder, num_records=2)

[13:18:21] [INFO] 🖼️ Preview generation in progress
[13:18:21] [INFO] ✅ Validation passed
[13:18:21] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph
[13:18:21] [INFO] 🩺 Running health checks for models...
[13:18:21] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-nano-v3'...
[13:18:22] [INFO]   |-- ✅ Passed!
[13:18:22] [INFO] 🎲 Preparing samplers to generate 2 records across 6 columns
[13:18:22] [INFO] 📝 llm-text model config for column 'product_name'
[13:18:22] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'
[13:18:22] [INFO]   |-- model alias: 'nemotron-nano-v3'
[13:18:22] [INFO]   |-- model provider: 'nvidia'
[13:18:22] [INFO]   |-- inference parameters:
[13:18:22] [INFO]   |  |-- generation_type=chat-completion
[13:18:22] [INFO]   |  |-- max_parallel_requests=4
[13:18:22] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}
[13:18:22] [INFO]   |  |-- temperature=1.00
[13:18:22] [INFO]   |  |-- top_p=1.00
[13:18:22] [INFO]   |  |-- max_tokens=2048
[13:18:22] [INFO] ⚡️ Processing llm-text column 'product_name' with 4 concurrent workers
[13:18:22] [INFO] ⏱️ llm-text column 'product_name' will report progress after each record
[13:18:22] [INFO]   |-- 🚗 llm-text column 'product_name' progress: 1/2 (50%) complete, 1 ok, 0 failed, 6.29 rec/s, eta 0.2s
[13:18:22] [INFO]   |-- 🚀 llm-text column 'product_name' progress: 2/2 (100%) complete, 2 ok, 0 failed, 10.26 rec/s, eta 0.0s
[13:18:22] [INFO] 📝 llm-text model config for column 'customer_review'
[13:18:22] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'
[13:18:22] [INFO]   |-- model alias: 'nemotron-nano-v3'
[13:18:22] [INFO]   |-- model provider: 'nvidia'
[13:18:22] [INFO]   |-- inference parameters:
[13:18:23] [INFO]   |  |-- generation_type=chat-completion
[13:18:23] [INFO]   |  |-- max_parallel_requests=4
[13:18:23] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}
[13:18:23] [INFO]   |  |-- temperature=1.00
[13:18:23] [INFO]   |  |-- top_p=1.00
[13:18:23] [INFO]   |  |-- max_tokens=2048
[13:18:23] [INFO] ⚡️ Processing llm-text column 'customer_review' with 4 concurrent workers
[13:18:23] [INFO] ⏱️ llm-text column 'customer_review' will report progress after each record
[13:18:23] [INFO]   |-- ⛅ llm-text column 'customer_review' progress: 1/2 (50%) complete, 1 ok, 0 failed, 2.08 rec/s, eta 0.5s
[13:18:26] [INFO]   |-- ☀️ llm-text column 'customer_review' progress: 2/2 (100%) complete, 2 ok, 0 failed, 0.53 rec/s, eta 0.0s
[13:18:27] [INFO] 📊 Model usage summary:
[13:18:27] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b
[13:18:27] [INFO]   |-- tokens: input=351, output=690, total=1041, tps=195
[13:18:27] [INFO]   |-- requests: success=4, failed=0, total=4, rpm=45
[13:18:27] [INFO] 📐 Measuring dataset column statistics:
[13:18:27] [INFO]   |-- 🎲 column: 'product_category'
[13:18:27] [INFO]   |-- 🎲 column: 'product_subcategory'
[13:18:27] [INFO]   |-- 🎲 column: 'target_age_range'
[13:18:27] [INFO]   |-- 🎲 column: 'customer'
[13:18:27] [INFO]   |-- 🎲 column: 'number_of_stars'
[13:18:27] [INFO]   |-- 🎲 column: 'review_style'
[13:18:27] [INFO]   |-- 📝 column: 'product_name'
[13:18:29] [INFO]   |-- 📝 column: 'customer_review'
[13:18:29] [INFO] 🏆 Preview complete!

In [13]:
# Run this cell multiple times to cycle through the 2 preview records.
preview.display_sample_record()

                                              Generated Columns
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name                ┃ Value                                                                                ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category    │ Books                                                                                │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ product_subcategory │ Non-Fiction                                                                          │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ target_age_range    │ 50-65                                                                                │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ customer            │ {                                                                                    │
│                     │     'uuid': '873df74f-4be0-48b6-a317-6bec827095a2',                                  │
│                     │     'locale': 'en_US',                                                               │
│                     │     'first_name': 'Samantha',                                                        │
│                     │     'last_name': 'Singh',                                                            │
│                     │     'middle_name': None,                                                             │
│                     │     'sex': 'Female',                                                                 │
│                     │     'street_number': '309',                                                          │
│                     │     'street_name': 'Peterson Brooks',                                                │
│                     │     'city': 'Priscillaville',                                                        │
│                     │     'state': 'Washington',                                                           │
│                     │     'postcode': '42332',                                                             │
│                     │     'age': 59,                                                                       │
│                     │     'birth_date': '1966-12-06',                                                      │
│                     │     'country': 'Guadeloupe',                                                         │
│                     │     'marital_status': 'married_present',                                             │
│                     │     'education_level': 'secondary_education',                                        │
│                     │     'unit': '',                                                                      │
│                     │     'occupation': 'Recruitment consultant',                                          │
│                     │     'phone_number': '+1-439-629-5316x1289',                                          │
│                     │     'bachelors_field': 'no_degree'                                                   │
│                     │ }                                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ number_of_stars     │ 2                                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ review_style        │ rambling                                                                             │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ product_name        │ Timeless Wisdom Chronicles                                                           │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ customer_review     │ Ah, dear chronicle seekers, gather 'round while I sip my lukewarm chamomile and      │
│                     │ contemplate this curious little volume that arrived wrapped in such promising paper  │
│                     │ and an embossed emblem that *almost* made me think of my late husband's pocket       │
│                     │ watch, though it was rather too shiny for a timepiece. I’d been so *eager*—you see,  │
│                     │ at my age, with the garden needing pruning and my cat, Mittens, requiring constant   │
│                     │ tuna negotiations, I craved something to truly *witness* the passage of time, not    │
│                     │ just mark it on a calendar (though, bless him, he always did it with a pen that      │
│                     │ wrote like a drunken sparrow). I imagined it would be like listening to the river in │
│                     │ my backyard whisper its secrets while I rocked in my favorite wicker chair, the one  │
│                     │ that creaks like a well-worn library book.                                           │
│                     │                                                                                      │
│                     │ But oh, the *slow* pace of it! I started reading after dinner, the way I do with my  │
│                     │ dear Agatha Christie, but instead of a clever little prune-suggestion in the margins │
│                     │ or a warm "I see you've found a clue!" I was met with sentences so long and winding  │
│                     │ they made my knitting needles feel like they were performing a ballet. One page      │
│                     │ described a philosopher's contemplation of moonlight on a pond *while* listing every │
│                     │ single bird species that ever nested near a water lily, and I simply set it aside on │
│                     │ the side table next to my thermos of tea, thinking, "Well, that's not what I         │
│                     │ ordered. I wanted *something* to hold in my hands while I watched the roses wilt,    │
│                     │ not a textbook disguised as a toaster manual." It felt less like a chronicle and     │
│                     │ more like being asked to listen to a lecture delivered by a very earnest, slightly   │
│                     │ confused librarian who’d forgotten to bring his spectacles.                          │
│                     │                                                                                      │
│                     │ So, I gave it a rating of two stars—two stars for the *idea* of it, and two stars    │
│                     │ for the lovely paper it was printed on, which smelled faintly of old books and the   │
│                     │ promise of something meaningful. But truly, it was about as useful to me as a screen │
│                     │ door on a submarine, and I’d rather spend my Tuesday afternoons polishing the brass  │
│                     │ doorknob on my front door than decipher those rambling musings. I’ll tuck it gently  │
│                     │ back into its box, perhaps to be a paperweight for my favorite teapot, but I doubt   │
│                     │ I’ll pick it up again until I'm feeling particularly nostalgic for the days when I   │
│                     │ *did* read all of Dickens without needing to check my watch for the kettle. It’s a   │
│                     │ shame, for I so *wanted* to love it, like a child reaching for a shiny balloon that  │
│                     │ deflates the moment you touch it. Now, if you'll excuse me, I must go see if my      │
│                     │ daffodils have decided to bloom in the right season.                                 │
└─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────┘

In [14]:
# The preview dataset is available as a pandas DataFrame.
preview.dataset

,product_category,product_subcategory,target_age_range,customer,number_of_stars,review_style,product_name,customer_review
0,Books,Non-Fiction,50-65,{'uuid': '873df74f-4be0-48b6-a317-6bec827095a2...,2,rambling,Timeless Wisdom Chronicles,"Ah, dear chronicle seekers, gather 'round whil..."
1,Books,Non-Fiction,18-25,{'uuid': '96480db0-a832-492c-88b0-0da542123f5c...,3,brief,Mindful Pages,"I gave Mindful Pages 3 stars. It's a nice, sim..."

### 📊 Analyze the generated data

- Data Designer automatically generates a basic statistical analysis of the generated data.

- This analysis is available via the `analysis` property of generation result objects.

In [15]:
# Print the analysis as a table.
preview.analysis.to_report()

──────────────────────────────────────── 🎨 Data Designer Dataset Profile ─────────────────────────────────────────


                                                 Dataset Overview
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ number of records               ┃ number of columns               ┃ percent complete records                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 2                               │ 8                               │ 100.0%                                      │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────────────────┘


                                                🎲 Sampler Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                    ┃       data type ┃            number unique values ┃               sampler type ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category               │          string │                       1 (50.0%) │                   category │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ product_subcategory            │          string │                       1 (50.0%) │                subcategory │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ target_age_range               │          string │                      2 (100.0%) │                   category │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ customer                       │            dict │                      2 (100.0%) │          person_from_faker │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ number_of_stars                │             int │                      2 (100.0%) │                    uniform │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ review_style                   │          string │                      2 (100.0%) │                   category │
└────────────────────────────────┴─────────────────┴─────────────────────────────────┴────────────────────────────┘


                                                📝 LLM-Text Columns
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                       ┃               ┃                            ┃     prompt tokens ┃      completion tokens ┃
┃ column name           ┃     data type ┃       number unique values ┃        per record ┃             per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_name          │        string │                 2 (100.0%) │      74.0 +/- 0.0 │            3.5 +/- 0.7 │
├───────────────────────┼───────────────┼────────────────────────────┼───────────────────┼────────────────────────┤
│ customer_review       │        string │                 2 (100.0%) │      68.5 +/- 2.5 │        331.5 +/- 365.6 │
└───────────────────────┴───────────────┴────────────────────────────┴───────────────────┴────────────────────────┘


╭────────────────────────────────────────────────── Table Notes ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  1. All token statistics are based on a sample of max(1000, len(dataset)) records.                              │
│  2. Tokens are calculated using tiktoken's cl100k_base tokenizer.                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

### 🆙 Scale up!

- Happy with your preview data?

- Use the `create` method to submit larger Data Designer generation jobs.

In [16]:
results = data_designer.create(config_builder, num_records=10, dataset_name="tutorial-1")

[13:18:55] [INFO] 🎨 Creating Data Designer dataset
[13:18:55] [INFO] ✅ Validation passed
[13:18:55] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph
[13:18:55] [INFO] 🩺 Running health checks for models...
[13:18:55] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-nano-v3'...
[13:18:55] [INFO]   |-- ✅ Passed!
[13:18:55] [INFO] ⏳ Processing batch 1 of 1
[13:18:55] [INFO] 🎲 Preparing samplers to generate 10 records across 6 columns
[13:18:55] [INFO] 📝 llm-text model config for column 'product_name'
[13:18:55] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'
[13:18:55] [INFO]   |-- model alias: 'nemotron-nano-v3'
[13:18:55] [INFO]   |-- model provider: 'nvidia'
[13:18:55] [INFO]   |-- inference parameters:
[13:18:55] [INFO]   |  |-- generation_type=chat-completion
[13:18:55] [INFO]   |  |-- max_parallel_requests=4
[13:18:55] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}
[13:18:55] [INFO]   |  |-- temperature=1.00
[13:18:55] [INFO]   |  |-- top_p=1.00
[13:18:55] [INFO]   |  |-- max_tokens=2048
[13:18:55] [INFO] ⚡️ Processing llm-text column 'product_name' with 4 concurrent workers
[13:18:55] [INFO] ⏱️ llm-text column 'product_name' will report progress after each record
[13:18:55] [INFO]   |-- 🐱 llm-text column 'product_name' progress: 1/10 (10%) complete, 1 ok, 0 failed, 6.03 rec/s, eta 1.5s
[13:18:55] [INFO]   |-- 🐱 llm-text column 'product_name' progress: 2/10 (20%) complete, 2 ok, 0 failed, 10.42 rec/s, eta 0.8s
[13:18:56] [INFO]   |-- 😺 llm-text column 'product_name' progress: 3/10 (30%) complete, 3 ok, 0 failed, 8.90 rec/s, eta 0.8s
[13:18:56] [INFO]   |-- 😺 llm-text column 'product_name' progress: 4/10 (40%) complete, 4 ok, 0 failed, 10.37 rec/s, eta 0.6s
[13:18:56] [INFO]   |-- 😸 llm-text column 'product_name' progress: 5/10 (50%) complete, 5 ok, 0 failed, 11.94 rec/s, eta 0.4s
[13:18:56] [INFO]   |-- 😸 llm-text column 'product_name' progress: 6/10 (60%) complete, 6 ok, 0 failed, 11.70 rec/s, eta 0.3s
[13:18:56] [INFO]   |-- 😸 llm-text column 'product_name' progress: 7/10 (70%) complete, 7 ok, 0 failed, 13.21 rec/s, eta 0.2s
[13:18:56] [INFO]   |-- 😼 llm-text column 'product_name' progress: 8/10 (80%) complete, 8 ok, 0 failed, 14.89 rec/s, eta 0.1s
[13:18:56] [INFO]   |-- 😼 llm-text column 'product_name' progress: 9/10 (90%) complete, 9 ok, 0 failed, 13.34 rec/s, eta 0.1s
[13:18:56] [INFO]   |-- 🦁 llm-text column 'product_name' progress: 10/10 (100%) complete, 10 ok, 0 failed, 9.43 rec/s, eta 0.0s
[13:18:56] [INFO] 📝 llm-text model config for column 'customer_review'
[13:18:56] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'
[13:18:56] [INFO]   |-- model alias: 'nemotron-nano-v3'
[13:18:56] [INFO]   |-- model provider: 'nvidia'
[13:18:56] [INFO]   |-- inference parameters:
[13:18:56] [INFO]   |  |-- generation_type=chat-completion
[13:18:56] [INFO]   |  |-- max_parallel_requests=4
[13:18:56] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}
[13:18:56] [INFO]   |  |-- temperature=1.00
[13:18:56] [INFO]   |  |-- top_p=1.00
[13:18:56] [INFO]   |  |-- max_tokens=2048
[13:18:56] [INFO] ⚡️ Processing llm-text column 'customer_review' with 4 concurrent workers
[13:18:56] [INFO] ⏱️ llm-text column 'customer_review' will report progress after each record
[13:18:57] [INFO]   |-- 🐱 llm-text column 'customer_review' progress: 1/10 (10%) complete, 1 ok, 0 failed, 3.30 rec/s, eta 2.7s
[13:18:58] [INFO]   |-- 🐱 llm-text column 'customer_review' progress: 2/10 (20%) complete, 2 ok, 0 failed, 1.37 rec/s, eta 5.8s
[13:18:58] [INFO]   |-- 😺 llm-text column 'customer_review' progress: 3/10 (30%) complete, 3 ok, 0 failed, 1.71 rec/s, eta 4.1s
[13:18:59] [INFO]   |-- 😺 llm-text column 'customer_review' progress: 4/10 (40%) complete, 4 ok, 0 failed, 1.61 rec/s, eta 3.7s
[13:19:00] [INFO]   |-- 😸 llm-text column 'customer_review' progress: 5/10 (50%) complete, 5 ok, 0 failed, 1.43 rec/s, eta 3.5s
[13:19:00] [INFO]   |-- 😸 llm-text column 'customer_review' progress: 6/10 (60%) complete, 6 ok, 0 failed, 1.55 rec/s, eta 2.6s
[13:19:01] [INFO]   |-- 😸 llm-text column 'customer_review' progress: 7/10 (70%) complete, 7 ok, 0 failed, 1.56 rec/s, eta 1.9s
[13:19:01] [INFO]   |-- 😼 llm-text column 'customer_review' progress: 8/10 (80%) complete, 8 ok, 0 failed, 1.74 rec/s, eta 1.1s
[13:19:03] [INFO]   |-- 😼 llm-text column 'customer_review' progress: 9/10 (90%) complete, 9 ok, 0 failed, 1.36 rec/s, eta 0.7s
[13:19:03] [INFO]   |-- 🦁 llm-text column 'customer_review' progress: 10/10 (100%) complete, 10 ok, 0 failed, 1.41 rec/s, eta 0.0s
[13:19:04] [INFO] 📊 Model usage summary:
[13:19:04] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b
[13:19:04] [INFO]   |-- tokens: input=1858, output=4498, total=6356, tps=712
[13:19:04] [INFO]   |-- requests: success=20, failed=0, total=20, rpm=134
[13:19:04] [INFO] 📐 Measuring dataset column statistics:
[13:19:04] [INFO]   |-- 🎲 column: 'product_category'
[13:19:04] [INFO]   |-- 🎲 column: 'product_subcategory'
[13:19:04] [INFO]   |-- 🎲 column: 'target_age_range'
[13:19:04] [INFO]   |-- 🎲 column: 'customer'
[13:19:04] [INFO]   |-- 🎲 column: 'number_of_stars'
[13:19:04] [INFO]   |-- 🎲 column: 'review_style'
[13:19:04] [INFO]   |-- 📝 column: 'product_name'
[13:19:04] [INFO]   |-- 📝 column: 'customer_review'

In [17]:
# Load the generated dataset as a pandas DataFrame.
dataset = results.load_dataset()

dataset.head()

,product_category,product_subcategory,target_age_range,customer,number_of_stars,review_style,product_name,customer_review
0,Books,Classics,65+,"{'age': 31, 'bachelors_field': 'education', 'b...",1,detailed,Timeless Tales Library The Golden Page Colle...,I bought the **Timeless Tales Library** market...
1,Clothing,Activewear,35-50,"{'age': 38, 'bachelors_field': 'no_degree', 'b...",3,detailed,ElevateMotion Adult Activewear Tee,"I’m Michelle from East Amanda, Nebraska. I’m 3..."
2,Clothing,Winter Coats,18-25,"{'age': 70, 'bachelors_field': 'stem', 'birth_...",3,detailed,Midnight Aurora Coat,Midnight Aurora Coat – 3 Stars I bought the...
3,Electronics,Laptops,25-35,"{'age': 35, 'bachelors_field': 'arts_humanitie...",3,brief,ZenithPro Ultrabook,ZenithPro Ultrabook — nice screen and solid bu...
4,Home & Kitchen,Cookware,25-35,"{'age': 24, 'bachelors_field': 'no_degree', 'b...",5,rambling,ThermoFusion 6‑Piece Copper‑Core Skillet Set,I just got the ThermoFusion 6‑Piece Copper‑Cor...

In [18]:
# Load the analysis results into memory.
analysis = results.load_analysis()

analysis.to_report()

──────────────────────────────────────── 🎨 Data Designer Dataset Profile ─────────────────────────────────────────


                                                 Dataset Overview
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ number of records               ┃ number of columns               ┃ percent complete records                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 10                              │ 8                               │ 100.0%                                      │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────────────────┘


                                                🎲 Sampler Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                    ┃       data type ┃            number unique values ┃               sampler type ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category               │          string │                       4 (40.0%) │                   category │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ product_subcategory            │          string │                       7 (70.0%) │                subcategory │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ target_age_range               │          string │                       5 (50.0%) │                   category │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ customer                       │            dict │                     10 (100.0%) │          person_from_faker │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ number_of_stars                │             int │                       4 (40.0%) │                    uniform │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ review_style                   │          string │                       4 (40.0%) │                   category │
└────────────────────────────────┴─────────────────┴─────────────────────────────────┴────────────────────────────┘


                                                📝 LLM-Text Columns
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                       ┃               ┃                            ┃     prompt tokens ┃      completion tokens ┃
┃ column name           ┃     data type ┃       number unique values ┃        per record ┃             per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_name          │        string │                10 (100.0%) │      74.0 +/- 0.9 │           6.5 +/- 14.5 │
├───────────────────────┼───────────────┼────────────────────────────┼───────────────────┼────────────────────────┤
│ customer_review       │        string │                10 (100.0%) │     72.0 +/- 13.9 │        362.0 +/- 287.5 │
└───────────────────────┴───────────────┴────────────────────────────┴───────────────────┴────────────────────────┘


╭────────────────────────────────────────────────── Table Notes ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  1. All token statistics are based on a sample of max(1000, len(dataset)) records.                              │
│  2. Tokens are calculated using tiktoken's cl100k_base tokenizer.                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

## ⏭️ Next Steps

Now that you've seen the basics of Data Designer, check out the following notebooks to learn more about:

- [Structured outputs and jinja expressions](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/2-structured-outputs-and-jinja-expressions/)

- [Seeding synthetic data generation with an external dataset](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/3-seeding-with-a-dataset/)

- [Providing images as context](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/4-providing-images-as-context/)

- [Generating images](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/5-generating-images/)